/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlysinhvien;

import dao.BangPhucKhaoDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import pojo.BangPhucKhao;
import pojo.PhucKhao;
import dao.PhucKhaoDAO;
import javax.swing.JOptionPane;
import pojo.TaiKhoan;


/**
 *
 * @author yumil
 */
public class FormPhucKhao extends javax.swing.JFrame {

    /*
     * Creates new form PhucKhao
     */
    private int idBangPhucKhao;
    private QuanLyPhucKhao qlpk;
    private final String[] columnNames = {
        "STT", "ID", "MSSV", "Họ Tên", "Môn Học", "Cột Điểm", "Điểm Đề Nghị", "Lý Do", "Trạng Thái"
    };
    public FormPhucKhao() {
        initComponents();
    }

    public FormPhucKhao(QuanLyPhucKhao qlpk, String ID,int per) {
        this.setResizable(false);
        this.qlpk = qlpk;
        this.idBangPhucKhao =  Integer.parseInt(ID);
        this.qlpk.setVisible(false);
        initComponents();
         initLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jHeader = new javax.swing.JLabel();
        jPannelViewReexamine = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtMSSV = new javax.swing.JTextField();
        jtxtHoTen = new javax.swing.JTextField();
        jtxtCourse = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtRowScore = new javax.swing.JTextField();
        jtxtDiemDeNghi = new javax.swing.JTextField();
        jcbStatus = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxLyDo = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jbtnCapNhat = new javax.swing.JButton();
        jtxtID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableBangPhucKhao = new javax.swing.JTable();
        jbtnThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jHeader.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jHeader.setText("Phúc Khảo");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setText("MSSV:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Họ tên:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setText("Môn học:");

        jtxtMSSV.setEnabled(false);
        jtxtMSSV.setMinimumSize(new java.awt.Dimension(6, 24));

        jtxtHoTen.setEnabled(false);

        jtxtCourse.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setText("Cột điểm:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("Điểm đề nghị:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel6.setText("Trạng thái:");

        jtxtRowScore.setEnabled(false);
        jtxtRowScore.setMinimumSize(new java.awt.Dimension(6, 24));

        jtxtDiemDeNghi.setEnabled(false);

        jcbStatus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Đã cập nhật", "Không cập nhật", "Chưa Xem" }));

        jtxLyDo.setColumns(20);
        jtxLyDo.setRows(5);
        jtxLyDo.setEnabled(false);
        jScrollPane2.setViewportView(jtxLyDo);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Lý do:");

        jbtnCapNhat.setText("Cập nhật");
        jbtnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCapNhatActionPerformed(evt);
            }
        });

        jtxtID.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtxtID.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel8.setText("ID:");

        javax.swing.GroupLayout jPannelViewReexamineLayout = new javax.swing.GroupLayout(jPannelViewReexamine);
        jPannelViewReexamine.setLayout(jPannelViewReexamineLayout);
        jPannelViewReexamineLayout.setHorizontalGroup(
            jPannelViewReexamineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPannelViewReexamineLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPannelViewReexamineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPannelViewReexamineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtID)
                    .addComponent(jtxtHoTen)
                    .addComponent(jtxtCourse)
                    .addComponent(jtxtMSSV, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPannelViewReexamineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGroup(jPannelViewReexamineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPannelViewReexamineLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jtxtRowScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPannelViewReexamineLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPannelViewReexamineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jcbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtDiemDeNghi))))
                .addGroup(jPannelViewReexamineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPannelViewReexamineLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPannelViewReexamineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPannelViewReexamineLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jbtnCapNhat)))
                        .addGap(68, 68, 68))
                    .addGroup(jPannelViewReexamineLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPannelViewReexamineLayout.setVerticalGroup(
            jPannelViewReexamineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPannelViewReexamineLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPannelViewReexamineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPannelViewReexamineLayout.createSequentialGroup()
                        .addGroup(jPannelViewReexamineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtRowScore, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPannelViewReexamineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jtxtMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)))
                        .addGap(18, 18, 18)
                        .addGroup(jPannelViewReexamineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jtxtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jtxtDiemDeNghi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPannelViewReexamineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jtxtCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jcbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPannelViewReexamineLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPannelViewReexamineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnCapNhat)
                    .addComponent(jtxtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtableBangPhucKhao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtableBangPhucKhao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableBangPhucKhaoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtableBangPhucKhao);

        jbtnThoat.setText("Thoát");
        jbtnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jPannelViewReexamine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(25, 25, 25))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbtnThoat)
                            .addGap(19, 19, 19)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnThoat)
                    .addComponent(jHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPannelViewReexamine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private void initLayout() {
        BangPhucKhao bpk = BangPhucKhaoDAO.kiemTraBangPhucKhao(idBangPhucKhao);
        List<PhucKhao> listPhucKhao = PhucKhaoDAO.getListPhucKhao(idBangPhucKhao);
        
        if (listPhucKhao.size() > 0) {
            int stt = 1;
            DefaultTableModel tableModel = new DefaultTableModel();
            tableModel.setColumnIdentifiers(columnNames);
            // "STT", "ID", "MSSV", "Họ Tên", "Môn Học", "Cột Điểm", "Điểm Đề Nghị", "Mô Tả", "Trạng Thái"
            for (PhucKhao pk : listPhucKhao) {
                String[] rows = new String[9];
                rows[0] = String.valueOf(stt);
                rows[1] = String.valueOf(pk.getId());
                rows[2] = pk.getMssv();
                rows[3] = pk.getHoTen();
                rows[4] = pk.getMonHoc();
                rows[5] = pk.getCotDiem();
                rows[6] = pk.getDiemMongMuon().toString();
                rows[7] = pk.getLyDo();
                rows[8] = pk.getTrangThai();

                tableModel.addRow(rows);
                stt++;
            }

            jtableBangPhucKhao.setModel(tableModel);
        } else {
            DefaultTableModel tableModel = new DefaultTableModel();
            tableModel.setColumnIdentifiers(columnNames);
            jtableBangPhucKhao.setModel(tableModel);
        }
    }
    private void jbtnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCapNhatActionPerformed
//         TODO add your handling code here:
        int id = Integer.valueOf(this.jtxtID.getText());
        PhucKhao pk = PhucKhaoDAO.getPhucKhao(id);
        if (pk != null) {
            String trangThai = (String) jcbStatus.getItemAt(jcbStatus.getSelectedIndex());
            pk.setTrangThai(trangThai);
            boolean checkUpdate = PhucKhaoDAO.updatePhucKhao(pk);
            if (checkUpdate) {
                JOptionPane.showMessageDialog(null, "Cập nhật thành công.", "Thông báo", JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Xảy ra lỗi cập nhật.", "Thông báo", JOptionPane.WARNING_MESSAGE);
            }
            initLayout();
        } else {
            JOptionPane.showMessageDialog(null, "Xảy ra lỗi cập nhật.", "Thông báo", JOptionPane.WARNING_MESSAGE);
            initLayout();
        }
    }//GEN-LAST:event_jbtnCapNhatActionPerformed

    private void jtableBangPhucKhaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableBangPhucKhaoMouseClicked
        // TODO add your handling code here:int selectRow = jtableBangPhucKhao.getSelectedRow();
            int selectRow = jtableBangPhucKhao.getSelectedRow();
        if (selectRow >= 0) {
            //"STT", "ID", "MSSV", "Họ Tên", "Môn Học", "Cột Điểm", "Điểm Đề Nghị", "Mô Tả", "Trạng Thái"
            String id = (String) jtableBangPhucKhao.getValueAt(selectRow, 1);
            this.jtxtID.setText(id);
            
            String mssv = (String) jtableBangPhucKhao.getValueAt(selectRow, 2);
            this.jtxtMSSV.setText(mssv);
            
            String name = (String) jtableBangPhucKhao.getValueAt(selectRow, 3);
            this.jtxtHoTen.setText(name);
            
            String course = (String) jtableBangPhucKhao.getValueAt(selectRow, 4);
            this.jtxtCourse.setText(course);
            
            String rowScore = (String) jtableBangPhucKhao.getValueAt(selectRow, 5);
            this.jtxtRowScore.setText(rowScore);
            
            String suggetScore = (String) jtableBangPhucKhao.getValueAt(selectRow, 6);
            this.jtxtDiemDeNghi.setText(suggetScore);
            
            String description = (String) jtableBangPhucKhao.getValueAt(selectRow, 7);
            this.jtxLyDo.setText(description);
            
            String status = (String) jtableBangPhucKhao.getValueAt(selectRow, 8);
            this.jcbStatus.setSelectedItem(status);
        } else {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn dòng để thực hiện", "Thông báo", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jtableBangPhucKhaoMouseClicked

    private void jbtnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnThoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new GiaoVu().setVisible(true);
    }//GEN-LAST:event_jbtnThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhucKhao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhucKhao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhucKhao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhucKhao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPhucKhao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jHeader;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPannelViewReexamine;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnCapNhat;
    private javax.swing.JButton jbtnThoat;
    private javax.swing.JComboBox jcbStatus;
    private javax.swing.JTable jtableBangPhucKhao;
    private javax.swing.JTextArea jtxLyDo;
    private javax.swing.JTextField jtxtCourse;
    private javax.swing.JTextField jtxtDiemDeNghi;
    private javax.swing.JTextField jtxtHoTen;
    private javax.swing.JTextField jtxtID;
    private javax.swing.JTextField jtxtMSSV;
    private javax.swing.JTextField jtxtRowScore;
    // End of variables declaration//GEN-END:variables
}
