/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlysinhvien;

import dao.BangPhucKhaoDAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojo.BangPhucKhao;

/**
 *
 * @author yumil
 */
public class QuanLyPhucKhao extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyPhucKhao
     */
    private final String[] columnNames = {
        "STT", "ID", "Ngày Bắt Đầu", "Ngày Kết Thúc", "Học Kỳ", "Năm Học", "Trạng Thái"
    };
    public QuanLyPhucKhao() {
        initComponents();
        initLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTitle = new javax.swing.JLabel();
        jpnPhucKhao = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcbHK = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jbtnAdd = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jcbTrangThai = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jNamHoc = new javax.swing.JTextField();
        jNgayKT = new javax.swing.JTextField();
        jNgayBD = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableReexamine = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTitle.setText("Quản Lý Phúc Khảo");
        jTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Từ Ngày:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Học Kỳ:");

        jcbHK.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbHK.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "HK1", "HK2", "HK3" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Năm học:");

        jbtnAdd.setText("Tạo lịch");
        jbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Trạng thái: ");

        jcbTrangThai.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbTrangThai.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Đang mở", "Đã dóng" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Đến Ngày:");

        javax.swing.GroupLayout jpnPhucKhaoLayout = new javax.swing.GroupLayout(jpnPhucKhao);
        jpnPhucKhao.setLayout(jpnPhucKhaoLayout);
        jpnPhucKhaoLayout.setHorizontalGroup(
            jpnPhucKhaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPhucKhaoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jpnPhucKhaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnPhucKhaoLayout.createSequentialGroup()
                        .addGroup(jpnPhucKhaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnPhucKhaoLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jpnPhucKhaoLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jcbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43)
                        .addGroup(jpnPhucKhaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jpnPhucKhaoLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jpnPhucKhaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jcbHK, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(129, 129, 129)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnPhucKhaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnAdd)
                    .addComponent(jNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNgayKT, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jpnPhucKhaoLayout.setVerticalGroup(
            jpnPhucKhaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPhucKhaoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jpnPhucKhaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcbHK, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jpnPhucKhaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnPhucKhaoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addGroup(jpnPhucKhaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnPhucKhaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jNgayKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnPhucKhaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jbtnAdd))
                    .addGroup(jpnPhucKhaoLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jpnPhucKhaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jcbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTableReexamine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableReexamine);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jpnPhucKhao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnPhucKhao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        Date NgayBD = null;
        try {
            NgayBD = formatter.parse(jNgayBD.getText().toString());
        } catch (ParseException ex) {
            Logger.getLogger(QuanLyPhucKhao.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Date NgayKT = null;
        try {
            NgayKT = formatter.parse(this.jNgayKT.getText());
        } catch (ParseException ex) {
            Logger.getLogger(QuanLyPhucKhao.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(NgayBD!= null && NgayKT !=null){
        String NgayBd = formatter.format(NgayBD);
        String NgayKt = formatter.format(NgayKT);
        System.out.printf(NgayKt);
        if (NgayKT.after(NgayBD)) {
            String hocKy = String.valueOf(jcbHK.getItemAt(jcbHK.getSelectedIndex()));
            String namHoc = this.jNamHoc.getText();
            
                // Thêm mới
                BangPhucKhao bpk = new BangPhucKhao(hocKy, namHoc, NgayBd,NgayKt, 1);
                boolean checkCreate = BangPhucKhaoDAO.themBangPhucKhao(bpk);
                if (checkCreate) {
                    JOptionPane.showMessageDialog(null, "Tạo lịch phúc khảo thành công.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    initLayout();
            }
        }
        } else {
            JOptionPane.showMessageDialog(null, "Lịch không hợp lệ", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jbtnAddActionPerformed

    private void initLayout() {
        List<BangPhucKhao> list = BangPhucKhaoDAO.getListBangPhucKhao();
        if (list.size() > 0) {
            int stt = 1;
            DefaultTableModel tableModel = new DefaultTableModel();
            tableModel.setColumnIdentifiers(columnNames);
            //  "STT", "ID", "From Date", "End Date", "Học Kỳ", "Năm Học", "Trạng Thái"
            for (BangPhucKhao tr : list) {
                String[] rows = new String[9];
                rows[0] = String.valueOf(stt);
                rows[1] = tr.getId()+"";
                rows[2] = tr.getNgayBatDau().toString();
                rows[3] = tr.getNgayKetThuc().toString();
                rows[4] = tr.getHocKy();
                rows[5] = tr.getNamHoc();
                if (tr.getTrangThai() == 1) {
                    rows[6] = "Đang mở";
                } else {
                    rows[6] = "Đã đóng";
                }

                tableModel.addRow(rows);
                stt++;
            }

            jTableReexamine.setModel(tableModel);
        } else {
            DefaultTableModel tableModel = new DefaultTableModel();
            tableModel.setColumnIdentifiers(columnNames);
            jTableReexamine.setModel(tableModel);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhucKhao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhucKhao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhucKhao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhucKhao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyPhucKhao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jNamHoc;
    private javax.swing.JTextField jNgayBD;
    private javax.swing.JTextField jNgayKT;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableReexamine;
    private javax.swing.JLabel jTitle;
    private javax.swing.JButton jbtnAdd;
    private javax.swing.JComboBox jcbHK;
    private javax.swing.JComboBox jcbTrangThai;
    private javax.swing.JPanel jpnPhucKhao;
    // End of variables declaration//GEN-END:variables
}
