/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlysinhvien;

import dao.LopHocDAO;
import dao.Lop_MonHocDAO;
import dao.SinhVienDAO;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import pojo.LopHoc;
import pojo.Lop_MonHoc;
import pojo.SinhVien;
        /**
 *
 * @author yumil
 */
public class themSinhVienMonHoc extends javax.swing.JFrame {

    /**
     * Creates new form themSinhVienMonHoc
     */
    private LopHoc lh;
    private String tenLopHoc = "";
    private String idMonHoc = "";
    
    public themSinhVienMonHoc() {
        initComponents();
    }
       public themSinhVienMonHoc(String lop) {
        this.tenLopHoc = lop;
        initComponents();
        addDataCombobox();
    }
    public themSinhVienMonHoc(String lop, String idMH) {
        this.tenLopHoc = lop;
        this.idMonHoc = idMH;
        initComponents();
        addDataCombobox();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtbHoTen = new javax.swing.JTextField();
        cbLop = new javax.swing.JComboBox();
        jrBtnNam = new javax.swing.JRadioButton();
        jrBtnNu = new javax.swing.JRadioButton();
        jtbCMND = new javax.swing.JTextField();
        jbtnThem = new javax.swing.JButton();
        jbtnThoat = new javax.swing.JButton();
        jcbMSSV = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Thêm sinh viên");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("MSSV");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Lớp");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Giới tính");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Họ tên");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("CMND");

        jtbHoTen.setActionCommand(null);
        jtbHoTen.setPreferredSize(new java.awt.Dimension(59, 30));

        cbLop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--" }));

        jrBtnNam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jrBtnNam.setText("Nam");

        jrBtnNu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jrBtnNu.setText("Nữ");

        jtbCMND.setPreferredSize(new java.awt.Dimension(59, 30));
        jtbCMND.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtbCMNDKeyTyped(evt);
            }
        });

        jbtnThem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnThem.setText("Thêm");
        jbtnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnThemActionPerformed(evt);
            }
        });

        jbtnThoat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnThoat.setText("Thoát");
        jbtnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnThoatActionPerformed(evt);
            }
        });

        jcbMSSV.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--" }));
        jcbMSSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMSSVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jbtnThem)
                .addGap(65, 65, 65)
                .addComponent(jbtnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(16, 16, 16)))
                            .addComponent(jLabel3))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtbCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jrBtnNam)
                                .addGap(39, 39, 39)
                                .addComponent(jrBtnNu))
                            .addComponent(jtbHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbLop, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbLop, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrBtnNam)
                    .addComponent(jrBtnNu))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnThem)
                    .addComponent(jbtnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jtbCMND, jtbHoTen});

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    private void jtbCMNDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbCMNDKeyTyped
        // TODO add your handling code here:    }     
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jtbCMNDKeyTyped

    private void addDataCombobox()
    {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.addElement(this.tenLopHoc);
        cbLop.setModel(model);
        // add data cho combobox mssv
        List<SinhVien> listSV = SinhVienDAO.layDanhSachSinhVien();
        DefaultComboBoxModel comboboxModel = new DefaultComboBoxModel();
        if (listSV.size() > 0) {
            for (SinhVien sv : listSV) {
                String MSSV = sv.getMSSV();
                comboboxModel.addElement(MSSV);
            }
            jcbMSSV.setModel(comboboxModel);
        } else {
            jcbMSSV.setModel(new javax.swing.DefaultComboBoxModel(new String[]{}));
        }
    }
    private void jbtnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnThemActionPerformed
        // TODO add your handling code here: String mssv = textMSSV.getText();
       String mssv = jcbMSSV.getSelectedItem().toString();
        Lop_MonHoc l = new Lop_MonHoc(tenLopHoc,mssv);
       if( Lop_MonHocDAO.addSinhVien(l))
       {
            JOptionPane.showMessageDialog(null, "Thêm Sinh Viên Thành Công :)");
       }
       else {
           JOptionPane.showMessageDialog(null, "Thêm Sinh Viên Thất Bại");
       }
    }//GEN-LAST:event_jbtnThemActionPerformed

    private void jbtnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnThoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbtnThoatActionPerformed

    private void jcbMSSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMSSVActionPerformed
        // TODO add your handling code here:
        String mssv = jcbMSSV.getSelectedItem().toString();
        SinhVien sv = SinhVienDAO.layThongTinSinhVien(mssv);
        System.out.printf(sv.getHoTen());
        jtbHoTen.setText(sv.getHoTen());
        jtbCMND.setText(sv.getCMND());
        if(sv.getGioiTinh() ==0){
        jrBtnNam.setSelected(true);
        jrBtnNu.setSelected(false);
        }
        else {
         jrBtnNam.setSelected(false);
        jrBtnNu.setSelected(true);
        }   
       
    }//GEN-LAST:event_jcbMSSVActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(themSinhVienMonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(themSinhVienMonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(themSinhVienMonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(themSinhVienMonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new themSinhVienMonHoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbLop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbtnThem;
    private javax.swing.JButton jbtnThoat;
    private javax.swing.JComboBox jcbMSSV;
    private javax.swing.JRadioButton jrBtnNam;
    private javax.swing.JRadioButton jrBtnNu;
    private javax.swing.JTextField jtbCMND;
    private javax.swing.JTextField jtbHoTen;
    // End of variables declaration//GEN-END:variables
}
